FROM node:22-alpine as build-stage
WORKDIR /app
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install && yarn cache clean -f
COPY . .
RUN yarn build

FROM node:18-alpine AS production-stage
WORKDIR /app
COPY --from=build-stage /app/dist ./dist
COPY --from=build-stage /app/src ./src
COPY --from=build-stage /app/node_modules ./node_modules
COPY --from=build-stage /app/package* ./
COPY --from=build-stage /app/tsconfig* ./
ENTRYPOINT [ "yarn",'start:prod' ]